### ISSUE TITLE
Advice setting in fstab

### ISSUE THREAD

**Issue by bash99** [kazuhisya/dm-writeboost-rpm#6]
Hi, Kazuhisya

I found those settings is needed for a large cache(175G), as it tooks a long time for DWB init from the cache.
x-systemd.device-timeout=1200

my real setting
/dev/mapper/wbdev   /data                   xfs     noatime,nodiratime,nobarrier,auto,nofail,x-systemd.device-timeout=1200        0 0
, not so sure for nofail part, but without x-systemd.device-timeout=1200, the system won't boot. I use a safe value 1200, in my server, it' tooks 350 secs for DWB read the cache.

Quote from wiki.archlinux.org/index.php/Fstab
"x-systemd.device-timeout option. This is because the default device timeout is 90 seconds"

**Comment by kazuhisya** [comment]
Hi, @bash99

Thank you for a good advice.
btw, it takes a lot of time to `mount` instead of `dmsetup create` ?
If `mount` does not take time, `x-systemd.requires` may be used.

e.g.

```
/dev/mapper/wbdev /data defaults,x-systemd.requires=writeboost.service 0 0
```

**Comment by bash99** [comment]
@kazuhisya 
Yes, the time consume is on dmsetup part. So your option maybe better.

**Comment by kazuhisya** [comment]
Ok, I will add the explanation of this issue to the README later.
Thank you!
